### ISSUE TITLE
Вернуть настройки производительности sadrobot

### ISSUE THREAD

**Issue by mAXxtor** [sadrobot-team/sadrobot#12]
Настроить NGINX и Dajngo чтобы сайт отдавался максимально быстро

**Comment by alexandershovtyuk** [comment]
проверить обе CV через lighthouse в консоли

**Comment by aleksandrshovtyuk** [comment]
тестирую перевод в другой статус после коммента

**Comment by mAXxtor** [comment]
![Image](https://github.com/sadrobot-team/sadrobot/assets/15124821/3840d03c-86e6-43d7-852d-7d6e6bf5d0dc)


![Image](https://github.com/sadrobot-team/sadrobot/assets/15124821/b2cd1415-5d37-4be8-a5c1-6ac1ea319b66)


![Image](https://github.com/sadrobot-team/sadrobot/assets/15124821/c5737dbf-73c3-4640-8271-ec9d6e04a440)
