### ISSUE TITLE
Проверить/настриоть редиректы и обработку адресов для CV

### ISSUE THREAD

**Issue by mAXxtor** [sadrobot-team/sadrobot#13]
Для всех CV проверить корректность обработки адресов с обратным слешом и без

https://sadrobot.app/cv/maxxtor -> https://sadrobot.app/cv/maxxtor/
https://sadrobot.app/cv/elensasovtyuk-> https://sadrobot.app/cv/elensasovtyuk/

Код редиректа корректный

**Comment by alexandershovtyuk** [comment]
Проверить на двух cv

**Comment by alexandershovtyuk** [comment]
Done

![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/92911b07-185b-4f57-909c-40aee8f51a71)
