### ISSUE TITLE
Настроить страницы обработки ошибок для sadrobot

### ISSUE THREAD

**Issue by mAXxtor** [sadrobot-team/sadrobot#16]
404, 5xx

**Comment by alexandershovtyuk** [comment]
Задача не выполнена - вернул @sadrobot-team/devteam

**Comment by mAXxtor** [comment]
Fixed
[Дока ](https://www.notion.so/ashovtyuk/Custom-error-pages-in-Nginx-024a90a12fbf4a2a804b1fcf5f5e2c1f?pvs=4) актуальна
Как проверить:
[404](https://sadrobot.app/404/)
50x - проверял dummy методом. Уже отключил. Работает - просто поверить на слово)

**Comment by mAXxtor** [comment]
Также сделал на Hiremenow
Как проверить:
[404](https://hiremenow.ru/404/)
