### ISSUE TITLE
Update images in Elena Sadrobot CV

### ISSUE THREAD

**Issue by alexandershovtyuk** [sadrobot-team/sadrobot#18]
1. Фото-обложка для OG Image в секции META
2. Фавиконка для каждого CV

**Comment by alexandershovtyuk** [comment]
Превью

![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/dbcbbc71-a61d-47dc-8d2d-1a0628dffd34)
![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/c319e7fa-9778-46ff-bd8d-18767db7dd4c)
![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/6987dd5e-0fcc-44ec-948c-55063749bd06)

Ассеты подготовлены в архиве



[assets.zip](https://github.com/sadrobot-team/sadrobot/files/12743068/assets.zip)

**Comment by elenashovtyuk** [comment]
Нужно добавить favicon.ico для elenashow.

**Comment by alexandershovtyuk** [comment]
Фавиконка тут @elenashovtyuk 

[favicon.zip](https://github.com/sadrobot-team/sadrobot/files/12775331/favicon.zip)
