### ISSUE TITLE
Удалить протухший скрипт Github contributions

### ISSUE THREAD

**Issue by mAXxtor** [sadrobot-team/sadrobot#23]
Удалить к хуям js скрипт из статики и выпилить скрипт и див из кода

**Comment by alexandershovtyuk** [comment]
**Условие задачи не выполнено**


Блок с гитхабом есть на странице Макстора


![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/0644cb80-d7e2-45c6-9449-f82ab9cabb1f)

Блок с гитхабом есть на странице Елены

![Image](https://github.com/sadrobot-team/sadrobot/assets/4558175/64f4b6aa-f62f-4d29-a53c-2580f7bfa012)

**Comment by alexandershovtyuk** [comment]
done
